jersey_bidder/main/routes.py
import json
from flask import Blueprint, request, render_template, url_for,redirect
from flask_wtf import Form
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_user, current_user, logout_user, login_required
from jersey_bidder.models import FlaskUser
main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('/jersey_bidder/main/home.html')
    
@main.route("/")
@main.route("/faqpage")
def faq():
    return render_template('/jersey_bidder/main/faq.html')

# @main.route("/")
# @main.route("/test")
# def test():
#     roles = FlaskUser.query.first().roles
#     return render_template('/jersey_bidder/main/testingPage.html', roles=roles)

jersey_bidder/numbers/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_user, logout_user, login_required
from datetime import datetime
from flask_user import roles_required, current_user

# local
from jersey_bidder.models import User, Choice, JerseyNumber
from jersey_bidder.numbers.forms import biddingFormSenior, chopeNumberForm, allocateForm, biddingFormJunior
from jersey_bidder.numbers.utils import typeCastFormData
from jersey_bidder import db
from jersey_bidder.utils import getUser


numbers = Blueprint('numbers', __name__)


@numbers.route("/preference", methods=['GET', 'POST'])
def showNumber():
    currentUser = getUser(current_user)
    numbers = JerseyNumber.query.filter(
        JerseyNumber.gender_id == currentUser.gender_id).order_by(JerseyNumber.number).all()
        
    return render_template('/jersey_bidder/numbers/prefViewAll.html', title='Preference Page', numbers=numbers)


@numbers.route("/preference/<int:jerseyNumber_id>", methods=['GET', 'POST'])
def showSingleNumber(jerseyNumber_id):
    number = JerseyNumber.query.get_or_404(jerseyNumber_id)
    interestedUsers = User.query.filter(
        User.preference_id == number.id and User.gender_id == number.gender_id).all()
    return render_template('/jersey_bidder/numbers/prefViewSingleNumber.html', title='Preference Page', number=number, interestedUsers=interestedUsers)


@numbers.route("/preference/chope/<int:jerseyNumber_id>", methods=['GET', 'POST'])
def chopeSingleNumber(jerseyNumber_id):
    number = JerseyNumber.query.get_or_404(jerseyNumber_id)
    newNumber = number = JerseyNumber.query.get_or_404(jerseyNumber_id)
    currentUser = getUser(current_user)
    currentUser.preference_id = newNumber.id
    db.session.commit()

    return render_template('/jersey_bidder/numbers/prefChopeNumber.html', title='Chope', newNumber=newNumber)

@numbers.route("/bidder/choice", methods=['GET','POST'])
@roles_required('Bidder')
def routeYearToBid():
    currentUser = getUser(current_user)
    if currentUser.year > 1:
        return redirect(url_for('numbers.bidNumberSenior'))
    else:
        return redirect(url_for('numbers.bidNumberJunior'))


@numbers.route("/bidding/senior", methods=['GET', 'POST'])
@roles_required('Bidder')
def bidNumberSenior():

    # initialize form and populate choices
    form = biddingFormSenior()
    currentUser = getUser(current_user)
    
    form.firstChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.secondChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.thirdChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fourthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fifthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.wantUniqueNumber.choices = [(1,'Yes'),(2,'No')]

    # if current user has submitted a choice, redirect to editing page
    if currentUser.choice:
        return redirect(url_for('numbers.editNumberSenior')) 

    # fetch the current user's year for further validation, only 2+ years in IHG can choose unique option
    userYear = getUser(current_user).year

    if form.validate_on_submit():
        submitDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        #type cast an integer from form into bool, wantUniqueNumber is either True or False (bool)
        wantUniqueNumber = typeCastFormData(form.wantUniqueNumber.data)
        #update the user's "wantUniqueNumber" accordingly
        getUser(current_user).wantUniqueNumber = wantUniqueNumber

        choice = Choice(submitDatetime=submitDate, firstChoice=form.firstChoice.data, secondChoice=form.secondChoice.data,
                        thirdChoice=form.thirdChoice.data, fourthChoice=form.fourthChoice.data, fifthChoice=form.fifthChoice.data,
                        user_id=currentUser.id)

        db.session.add(choice)
        db.session.commit()

        successMessage = "Your submission has been registered."
        return render_template('/jersey_bidder/numbers/biddingSuccess.html', successMessage=successMessage)

    return render_template('/jersey_bidder/numbers/biddingPageSenior.html', title='Bidding', form=form, userYear=userYear)

@numbers.route("/bidding/junior", methods=['GET', 'POST'])
@roles_required('Bidder')
def bidNumberJunior():

    # initialize form and populate choices
    form = biddingFormJunior()
    currentUser = getUser(current_user)
    
    form.firstChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.secondChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.thirdChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fourthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fifthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    # if current user has submitted a choice, redirect to editing page
    if currentUser.choice:
        return redirect(url_for('numbers.editNumberJunior'))

    # fetch the current user's year for further validation, only 2+ years in IHG can choose unique option
    userYear = getUser(current_user).year

    if form.validate_on_submit():
        submitDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        choice = Choice(submitDatetime=submitDate, firstChoice=form.firstChoice.data, secondChoice=form.secondChoice.data,
                        thirdChoice=form.thirdChoice.data, fourthChoice=form.fourthChoice.data, fifthChoice=form.fifthChoice.data,
                        user_id=currentUser.id)

        db.session.add(choice)
        db.session.commit()

        successMessage = "Your submission has been registered."
        return render_template('/jersey_bidder/numbers/biddingSuccess.html', successMessage=successMessage)

    return render_template('/jersey_bidder/numbers/biddingPageJunior.html', title='Bidding', form=form, userYear=userYear)



@numbers.route("/bidding/editchoice/senior", methods=['GET', 'POST'])
@roles_required('Bidder')
def editNumberSenior():

    # get User Model from FlaskUser
    currentUser = getUser(current_user)

    # initialize form and populate choices
    form = biddingFormSenior()
    form.firstChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.secondChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.thirdChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fourthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fifthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.wantUniqueNumber.choices = [(1,'Yes'),(2,'No')]

    # fetch current users' previous choice and unique preference to display on the site 
    currentChoice = Choice.query.filter(
        Choice.user_id == currentUser.id).first()

    # fetch the current user's year for further validation
    userYear = getUser(current_user).year
    wantUniqueNumber = getUser(current_user).wantUniqueNumber

    if form.validate_on_submit():
        submitDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        #type cast an integer from form into bool, wantUniqueNumber is either True or False (bool)
        wantUniqueNumber = typeCastFormData(form.wantUniqueNumber.data)
        #update the user's "wantUniqueNumber" accordingly
        getUser(current_user).wantUniqueNumber = wantUniqueNumber

        newChoice = Choice(submitDatetime=submitDate, firstChoice=form.firstChoice.data, secondChoice=form.secondChoice.data,
                           thirdChoice=form.thirdChoice.data, fourthChoice=form.fourthChoice.data, fifthChoice=form.fifthChoice.data,
                           user_id=currentUser.id)



        # remove the previous submission and commit the latest one
        db.session.delete(currentChoice)
        db.session.add(newChoice)
        db.session.commit()

        successMessage = "Your previous submission has been updated"
        return render_template('/jersey_bidder/numbers/biddingSuccess.html', successMessage=successMessage)

jersey_bidder/user/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_user, logout_user, login_required
from flask_user import current_user

#local
from jersey_bidder.models import  User, Choice, FlaskUser
from jersey_bidder.user.forms import LoginForm
from jersey_bidder.utils import getUser


user = Blueprint('users', __name__)

@user.route("/login", methods=['GET','POST']) 
def login():
    form = LoginForm()
    if form.validate_on_submit():
        attemptedFlaskUser = FlaskUser.query.filter_by(username=form.userName.data).first()
        #if user and bcrypt.check_password_hash(user.password, form.password.data):
        if attemptedFlaskUser and form.password.data == attemptedFlaskUser.password:
            login_user(attemptedFlaskUser)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful, Please Check room number and password', 'danger')
    return render_template('/jersey_bidder/user/login.html', title='Login', form=form)

@user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

""" @user.route("/checkresult")
@login_required
def checkresult():
    user = getUser(current_user)
    return render_template("/jersey_bidder/user/checkResult.html", user=user) """

jersey_bidder/templates/allocateFailure.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-orange w3-center w3-opacity w3-padding-64">
    <h4>Overall statistics: </h4>
    <div>{{overallStats['totalAllocatedUserInYear']}} out of {{ overallStats['totalUserInYear']}} have been allocated
    </div>
    <br>
    <h4>Please deconflict the choices and run allocate again</h4>
</div>
<div class="w3-container w3-white w3-center w3-opacity w3-padding-32">
    <h3>Male Table</h3>
    <table class="w3-table jb-margin-center jb-table-width-70">
        <tr>
            <th>Name</th>
            <th>Year</th>
            <th>Choices</th>
            <th>Number</th>
        </tr>
        {% for user in failedMales %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.year }}</td>
            {% if user.choice %}
            <td>{{ user.choice.firstChoice }},
                {{ user.choice.secondChoice }},
                {{ user.choice.thirdChoice }},
                {{ user.choice.fourthChoice }},
                {{ user.choice.fifthChoice }}
            </td>
            {% else %}
            <td>
                -
            </td>
            {% endif %}
            <td>{{ user.jerseyNumber_id }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
    <h3>Female Table</h3>
    <table class="w3-table jb-margin-center jb-table-width-70">
        <tr>
            <th>Name</th>
            <th>Year</th>
            <th>Choices</th>
            <th>Number</th>
        </tr>
        {% for user in failedFemales %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.year }}</td>
            {% if user.choice %}
            <td>{{ user.choice.firstChoice }},
                {{ user.choice.secondChoice }},
                {{ user.choice.thirdChoice }},
                {{ user.choice.fourthChoice }},
                {{ user.choice.fifthChoice }}
            </td>
            {% else %}
            <td>
                -
            </td>
            {% endif %}
            <td>{{ user.jerseyNumber_id }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

jersey_bidder/templates/allocateSuccess.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-green w3-center w3-opacity w3-padding-64">
    <br><h4>No conflicts detected.</h4>
</div>
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-64">
    <table class="w3-table jb-margin-center jb-table-width-70">
        <tr>
            <th>Number</th>
            <th>Name</th>
            <th>Year</th>
            <th>roomNumber</th>
        </tr>
        {% for user in allUsersInYear %}
        <tr>
            <td>{{ user.jerseyNumber_id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.year}}</td>
            <td>{{ user.roomNumber }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

jersey_bidder/templates/checkResult.html
{% extends "layout.html" %}
{% block content %}
{% if user.jerseyNumber_id %}
<div class="w3-container w3-light-green w3-center w3-opacity w3-padding-64">
    <h4><br>
        Your assigned number is {{ user.jerseyNumber_id }}. 
        <br>Contact SMC for support if necessary.
    </h4>
</div>
{% else %}
<div class="w3-container w3-yellow w3-center w3-opacity w3-padding-64">
    <h4><br>
        We are still trying to allocate a number to you, please hold tight.
    </h4>
</div>
{% endif %}
{% endblock content %}

jersey_bidder/templates/generalErrorPage.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-yellow w3-center w3-opacity w3-padding-64">
    <br><h4>Unexpected Error Occured</h4>
    <br><h4>{{ errorMessage }}</h4>
    <a href="{{ url_for('useradmin.adminHome') }}"><br><h4>Go back to admin home page</h4></a>
</div>

{% endblock content %}

jersey_bidder/templates/layout.html
<!DOCTYPE html>

<head>
  {% block head %}
  {% endblock head %}
  <html lang="en">
  <title>Jersey Bidder</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/w3.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/jb.css')}}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <style>
    body,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: "Lato", sans-serif
    }

    .w3-bar,
    h1,
    button {
      font-family: "Montserrat", sans-serif
    }

    .fa-anchor,
    .fa-coffee {
      font-size: 200px
    }
  </style>
  {% block style %}
  {% endblock style %}
</head>

<body>
  <div class="w3-top">
    <div class="w3-bar w3-dark-grey w3-card w3-left-align w3-large">
      <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-amber"
        href="javascript:myFunction();" onclick="myFunctionShow()" title="Toggle Navigation Menu"><i
          class="fa fa-bars"></i></a>
      <a href="{{ url_for('main.home') }}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Home</a>
        <a href="{{ url_for('main.faq') }}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">FAQ</a>
      {% if current_user.is_authenticated %}
      {% if current_user.is_admin() %}
      <a href="{{ url_for('useradmin.adminHome')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Admin</a>
      {% else %}
      <a href="{{ url_for('numbers.showNumber')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Indicate Preference</a>
      <a href="{{ url_for('numbers.routeYearToBid')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Bid</a>
<!--       <a href="{{ url_for('users.checkresult')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Check Result</a> -->
      {% endif %}
      <a href="{{ url_for('users.logout')}}"
        class="w3-bar-item  w3-button w3-hide-small w3-padding-large w3-hover-white">Logout</a>
      {% endif %}
      {% if current_user.is_authenticated %}
      <div class="w3-bar-item w3-hide-small w3-padding-large jb-align-right">
          <i
          class="fa fa-child fa-lg w3-hover-opacity"></i> Hi {{current_user.getUser().name}}!</div>
      {% endif %}
    </div>

    <!-- Navbar on small screens -->
    <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
      <div class="w3-bar-item">
        <a href="{{ url_for('main.home') }}" class="w3-button ">Home</a>
        <a href="{{ url_for('main.faq') }}"
        class="w3-button">FAQ</a>
        {% if current_user.is_authenticated %}
        {% if current_user.is_admin() %}
        <a href="{{ url_for('useradmin.adminHome')}}" class="w3-button">Admin</a>
        {% else %}
        <a href="{{ url_for('numbers.showNumber')}}" class="w3-button">Indicate Preference</a>
        <a href="{{ url_for('numbers.routeYearToBid')}}" class="w3-button">Bid</a>
<!--         <a href="{{ url_for('users.checkresult')}}" class="w3-button">Check
          Result</a> -->
        {% endif %}
        <a href="{{ url_for('users.logout')}}" class="w3-button w3-padding-large">Logout</a>
        {% endif %}
      </div>
    </div>
  </div>

  <!-- Flash message block -->
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  <div class="w3-container w3-center w3-orange">
    <br><br><br>
    <span class="jb-font-size-60pts">{% for category,message in messages %}</span>
    <div class="{{ category }}">{{ message }}</div><br>
    {% endfor %}
  </div>
  {% endif %}
  {% endwith %}

  {% block content %}
  {% endblock content %}


  <!--   add on new blocks with this
    <div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
  </div> -->

  <!-- Footer -->
  <footer class="w3-container w3-padding-32 w3-center w3-opacity">
    <h5>Follow us on <a href="https://www.instagram.com/hehckers/"><i
          class="fa fa-instagram fa-lg w3-hover-opacity"></i></a> for more exciting updates! </h5>
    <p>Powered by EUSOFF HACKERS</a></p>
  </footer>

  <script>
    // Used to toggle the menu on small screens when clicking on the menu button
    function myFunction() {
      var x = document.getElementById("navDemo");
      if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
      } else {
        x.className = x.className.replace("w3-show", "");
      }
    }
    /* When the user clicks on the button, 
    toggle between hiding and showing the dropdown content */
    function myFunctionShow() {
      document.getElementById("myDropdown").classList.toggle("show");
    }
    // Close the dropdown if the user clicks outside of it
    window.onclick = function (event) {
      if (!event.target.matches('.dropbtn')) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        var i;
        for (i = 0; i < dropdowns.length; i++) {
          var openDropdown = dropdowns[i];
          if (openDropdown.classList.contains('show')) {
            openDropdown.classList.remove('show');
          }
        }
      }
    }
  </script>
  {% block script %}
  {% endblock script %}
</body>

jersey_bidder/templates/showFemaleResultByYear.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
        <h3>
            <br>List of year {{year_id}} users (Female)
        </h3>
</div>
<div class="w3-container w3-white w3-center w3-opacity w3-padding-16 jb-table-width-70 jb-margin-center">
        <h3>
            <br>List of year {{year_id}} users (Female)
        </h3>
        <table class="w3-table ">
            <tr>
                <th>Name</th>
                <th>roomNumber</th>
                <th>Year</th>
                <th>Points</th>
                <th>Sports</th>
                <th>Choices</th>
                <th></th>
            </tr>
            {% for user in usersByYear %}
            <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.roomNumber }}</td>
                <td>{{ user.year }}</td>
                <td>{{ user.points }}</td>
                <td>
                    {% for sport in user.sports %}
                    {{ sport.sportName }}
                    {% endfor %}
                </td>
                <td>
                    {{ user.choice.firstChoice }}
                    {{ user.choice.secondChoice }}
                    {{ user.choice.thirdChoice }}
                    {{ user.choice.fourthChoice }}
                    {{ user.choice.fifthChoice }}
                </td>
                <td classs="w3-button"><a href="{{url_for('useradmin.adminAssign', user_id=user.id)}}">Allocate</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

jersey_bidder/templates/showMaleResultByYear.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
        <h3>
            <br>List of year {{year_id}} users (Male)
        </h3>
</div>
<div class="w3-container w3-white w3-center w3-opacity w3-padding-16 jb-table-width-70 jb-margin-center">
        <table class="w3-table ">
            <tr>
                <th>Name</th>
                <th>roomNumber</th>
                <th>Year</th>
                <th>Points</th>
                <th>Sports</th>
                <th>Choices</th>
                <th></th>
            </tr>
            {% for user in usersByYear %}
            <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.roomNumber }}</td>
                <td>{{ user.year }}</td>
                <td>{{ user.points }}</td>
                <td>
                    {% for sport in user.sports %}
                    {{ sport.sportName }}
                    {% endfor %}
                </td>
                <td>
                    {{ user.choice.firstChoice }}
                    {{ user.choice.secondChoice }}
                    {{ user.choice.thirdChoice }}
                    {{ user.choice.fourthChoice }}
                    {{ user.choice.fifthChoice }}
                </td>
                <td classs="w3-button"><a href="{{url_for('useradmin.adminAssign', user_id=user.id)}}">Allocate</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}