jersey_bidder/useradmin/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField, SelectField
from wtforms.validators import DataRequired, Email, Length, EqualTo, ValidationError, InputRequired
from flask_login import current_user

class allocateForm(FlaskForm):
    yearToAllocate = SelectField('Year To Allocate', validators=[
                                 InputRequired()], coerce=int)
    submit = SubmitField('Go!')


class assignNumberForm(FlaskForm):
    assign = SelectField('Availible Numbers', validators=[
        DataRequired()], coerce=int)
    submit = SubmitField('Assign')

class chooseWaveForm(FlaskForm):
    waveToChoose = SelectField('Choose a wave', validators=[
                                 InputRequired()], coerce=int)
    submit = SubmitField('Go!')

jersey_bidder/useradmin/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, make_response
from flask_login import login_user, logout_user, login_required
from flask_user import current_user, roles_required
from datetime import datetime

# local
from jersey_bidder.models import User, Choice, JerseyNumber, FlaskUser, Role, FlaskUserRoles

from jersey_bidder.useradmin.forms import allocateForm, assignNumberForm
from jersey_bidder import db
from jersey_bidder.utils import getFlaskUser, getFlaskUserRole
from jersey_bidder.useradmin.utils import allocateByYear, generateMaleList, generateFemaleList, splitMaleAndFemale, \
        availNumbers, allocateNonUniqueNumberToUser, allocateUniqueNumberToUser, getStatsForYear, getHighestYear
from jersey_bidder.useradmin.CustomAllocationExceptions import AllocationError
from jersey_bidder.useradmin.outputUtils import create_userpassword_csv


useradmin = Blueprint('useradmin', __name__)


@useradmin.route("/useradmin/home", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def adminHome():
    return render_template('/jersey_bidder/useradmin/adminHome.html')


@useradmin.route("/useradmin/allocate", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def adminAllocate():
    form = allocateForm()
    form.yearToAllocate.choices = [(0, 0), (1, 1), (2, 2), (3, "3+")]

    if form.validate_on_submit():
        failedAllocateUsers = []
        selectYear = form.yearToAllocate.data
        try:
            failedAllocateUsers = allocateByYear(selectYear)
        except AllocationError as err:
            errString = str(err)
            return render_template('generalErrorPage.html', errorMessage = errString)

        if failedAllocateUsers != None:

            overallStats = getStatsForYear(selectYear)

            # get failed male and female users
            maleAndFemaleTuple = splitMaleAndFemale(failedAllocateUsers)
            failedMaleList = maleAndFemaleTuple[0]
            failedFemaleList = maleAndFemaleTuple[1]

            return render_template('/jersey_bidder/useradmin/allocateFailure.html', failedMales=failedMaleList, failedFemales=failedFemaleList, overallStats=overallStats)

        successMessage = "successfully allocated year " + str(form.yearToAllocate.data) + " students"

        allUsersInYear = User.query.filter(User.year == form.yearToAllocate.data).all()
        return render_template('/jersey_bidder/useradmin/allocateSuccess.html', successMessage=successMessage, allUsersInYear=allUsersInYear)

    message = 'Choose a year to allocate'
    return render_template('/jersey_bidder/useradmin/selectYear.html', message=message, form=form)

@useradmin.route("/useradmin/checkresult/malebyyear", methods=['GET','POST'])
@login_required
@roles_required('Admin')
def chooseYearToShowMale():
    form = allocateForm()
    form.yearToAllocate.choices = [(0, 0), (1, 1), (2, 2), (3, "3+")]

    if form.validate_on_submit():
        year = form.yearToAllocate.data

        return redirect(url_for('useradmin.showMaleByYear', year=year))

    message = 'Choose a year to display (male bidders)'
    return render_template('/jersey_bidder/useradmin/selectYear.html', message=message, form=form)

@useradmin.route("/useradmin/checkresult/malebyyear/chosenyear=<int:year>", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def showMaleByYear(year):
    usersByYear = []

    if year > 2:
        year = getHighestYear()
        while year > 3:
            usersByYear.extend(User.query.filter((User.year == year) & (User.gender_id == 1)).order_by(User.year.desc(), User.points.desc()).all())
            year = year - 1

    usersByYear.extend(User.query.filter((User.year == year) & (User.gender_id == 1)).order_by(User.year.desc(), User.points.desc()).all())
    return render_template('/jersey_bidder/useradmin/showMaleResultByYear.html', usersByYear=usersByYear, year=year)

@useradmin.route("/useradmin/checkresult/femalebyyear", methods=['GET','POST'])
@login_required
@roles_required('Admin')
def chooseYearToShowFemale():
    form = allocateForm()
    form.yearToAllocate.choices = [(0, 0), (1, 1), (2, 2), (3, "3+")]

    if form.validate_on_submit():
        year = form.yearToAllocate.data

        return redirect(url_for('useradmin.showFemaleByYear', year=year))

    message = 'Choose a year to display (female bidders)'
    return render_template('/jersey_bidder/useradmin/selectYear.html', message=message, form=form)

@useradmin.route("/useradmin/checkresult/femalebyyear/chosenyear=<int:year>", methods=['GET', 'POST'])
@login_required
def showFemaleByYear(year):
    usersByYear = []

    if year > 2:
        year = getHighestYear()
        while year > 3:
            usersByYear.extend(User.query.filter((User.year == year) & (User.gender_id == 2)).order_by(User.year.desc(), User.points.desc()).all())
            year = year - 1

    usersByYear.extend(User.query.filter((User.year == year) & (User.gender_id == 2)).order_by(User.year.desc(), User.points.desc()).all())
    return render_template('/jersey_bidder/useradmin/showFemaleResultByYear.html', usersByYear=usersByYear, year=year)

@useradmin.route("/useradmin/checkresult/fullmalelist", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def getAllMaleUsers():
    users = User.query.filter(User.gender_id == 1).order_by(User.year.desc(), User.points.desc()).all()
    return render_template('/jersey_bidder/useradmin/fullNameListMale.html', users=users)


@useradmin.route("/useradmin/checkresult/fullfemalelist", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def getAllFemaleUsers():
    users = User.query.filter(User.gender_id == 2).order_by(User.year.desc(), User.points.desc()).all()
    return render_template('/jersey_bidder/useradmin/fullNameListFemale.html', users=users)


@useradmin.route("/useradmin/checkresult/conflict/male", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def getConflictMale():
    conflictUsers = User.query.filter(
        (User.gender_id == 1) & (User.jerseyNumber_id == None) & (User.choice != None)).all()

    return render_template('/jersey_bidder/useradmin/conflictUser.html', conflictUsers=conflictUsers, gender='male')


@useradmin.route("/useradmin/checkresult/conflict/female", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def getConflictFemale():
    conflictUsers = User.query.filter(
        (User.gender_id == 2) & (User.jerseyNumber_id == None) & (User.choice != None)).all()

    return render_template('/jersey_bidder/useradmin/conflictUser.html', conflictUsers=conflictUsers, gender='female')

@useradmin.route("/useradmin/checkresult/conflict/all", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def getConflictAll():
    conflictUsers = User.query.filter(User.jerseyNumber_id == None).all()

    return render_template('/jersey_bidder/useradmin/conflictUser.html', conflictUsers=conflictUsers)

@useradmin.route("/useradmin/adminassign/<int:user_id>", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def adminAssign(user_id):
    user = User.query.filter(User.id == user_id).first()
    listOfAvailNumbers = availNumbers(user)

    form = assignNumberForm()
    form.assign.choices = [(entries.number, entries.number)
                           for entries in listOfAvailNumbers]
    number = form.assign.data

    if form.validate_on_submit():
        if user.year == 1 or user.year == 2:
            allocateNonUniqueNumberToUser(number, user)
        else:
            allocateUniqueNumberToUser(number, user)

        db.session.commit()
        return render_template('/jersey_bidder/useradmin/adminAssignSuccess.html', user=user, number=number)

    return render_template('/jersey_bidder/useradmin/allocateSingleUser.html', user=user, listOfAvailNumbers=listOfAvailNumbers, form=form)

@useradmin.route("/useradmin/deactivatebyyear", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def chooseYearToDeactivate():
    form = allocateForm()
    form.yearToAllocate.choices = [(0, 0), (1, 1), (2, 2), (3, "3+")]

    if form.validate_on_submit():
        year = form.yearToAllocate.data
        return redirect(url_for('useradmin.deactivateByYear', year=year))

    message = 'Choose a year to deactivate'
    return render_template('/jersey_bidder/useradmin/selectYear.html', message=message, form=form)

@useradmin.route("/jersey_bidder//useradmin/deactivate/<int:year>", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def deactivateByYear(year):
    #deactivate users by year
    rawUsers = []

    if year > 2:
        year = getHighestYear()
        while year > 3:
            rawUsers.extend(User.query.filter(User.year==year).all())
            year = year - 1

    rawUsers.extend(User.query.filter(User.year==year).all())
    userlist = []
    bidderRole = Role.query.filter(Role.name == "Bidder").first()

    for user in rawUsers:
        flaskUser = getFlaskUser(user)
        userlist.append(flaskUser)
    for flaskUser in userlist:
        print(flaskUser.id)
        print(flaskUser.roles)
        if bidderRole in flaskUser.roles:
            flaskUser.roles.remove(bidderRole)

    db.session.commit()
    
    successMessage = "All year " + str(year) + " users have been deactivated. They can no longer submit bidding requests and edit their previous submissions." 
    return render_template('/jersey_bidder/useradmin/adminChangeAuthByYear.html', rawUsers=rawUsers, userlist=userlist, successMessage=successMessage)

@useradmin.route("/useradmin/activatebyyear", methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def chooseYearToActivate():
    form = allocateForm()
    form.yearToAllocate.choices = [(0, 0), (1, 1), (2, 2), (3, "3+")]

    if form.validate_on_submit():
        year = form.yearToAllocate.data
        return redirect(url_for('useradmin.activateByYear', year=year))

    message = 'Choose a year to activate'

jersey_bidder/templates/jersey_bidder/useradmin/adminAssignSuccess.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-green w3-center w3-opacity w3-padding-64">
    <br><h4>Manual Assign Successful!</h4>
    <br><h4>{{user.name}} is assigned with {{number}}</h4>
    <a href="{{ url_for('useradmin.adminHome') }}"><br><h4>Go back to admin home page</h4></a>
</div>

{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/adminChangeAuthByYear.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-green w3-center w3-opacity w3-padding-64">
    <h4>
        <br>{{ successMessage }}<br>
        <a href="{{url_for('useradmin.checkActiveUsers')}}">
            Check Current Active Users Here</a>
    </h4>
</div>
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
    <h2>List of users affected</h2><br>
    <table class="w3-table jb-table-width-70 jb-margin-center">
        <tr>
            <th>Name</th>
            <th>Year</th>
        </tr>
        {% for user in rawUsers %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.year }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/adminHome.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-Blue w3-center w3-opacity w3-padding-32">
    <br><br>
    <h3>
        Admin Page
    </h3>
</div>

<div class="w3-bar w3-light-grey w3-card w3-centered w3-large w3-padding-32">
    <a href="{{ url_for('useradmin.adminAllocate') }}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Allocate by year</a>
    <a href="{{url_for('useradmin.chooseYearToActivate')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Activate Users</a>
    <a href="{{url_for('useradmin.chooseYearToDeactivate')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Deactivate Users</a>
    <a href="{{url_for('useradmin.checkActiveUsers')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Check Current Active Users</a>
</div>
<div class="w3-bar w3-light-grey w3-card w3-centered w3-large w3-padding-32">
    <a href="{{url_for('useradmin.getConflictMale')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Conflicts (Male)</a>
    <a href="{{url_for('useradmin.getConflictFemale')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Conflicts (Female)</a>
    <a href="{{url_for('useradmin.getConflictAll')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Unallocated User</a>
</div>
<div class="w3-bar w3-white w3-card w3-centered w3-large w3-padding-32">
    <a href="{{url_for('useradmin.chooseYearToShowMale')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Display Male Bidders By Year</a>
    <a href="{{ url_for('useradmin.getAllMaleUsers') }}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">All
        Male User</a>
    <a href="{{url_for('useradmin.chooseYearToShowFemale')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">Display Female Bidders By Year</a>
    <a href="{{ url_for('useradmin.getAllFemaleUsers')}}"
        class="w3-bar-item w3-button w3-hide-small w3-padding-large">All Female User</a>
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/adminShowActiveUsers.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-64">
    <h2>List of active users</h2><br>
    <table class="w3-table jb-table-width-70 jb-margin-center">
        <tr>
            <th>Name</th>
            <th>Year</th>
        </tr>
        {% for user in activeUsers %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.year }}</td>
        </tr>
        {% endfor %}
    </table>
    
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/allocateFailure.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-orange w3-center w3-opacity w3-padding-64">
    <h4>Overall statistics: </h4>
    <div>{{overallStats['totalAllocatedUserInYear']}} out of {{ overallStats['totalUserInYear']}} have been allocated
    </div>
    <br>
    <h4>Please deconflict the choices and run allocate again</h4>
</div>
<div class="w3-container w3-white w3-center w3-opacity w3-padding-32">
    <h3>Male Table</h3>
    <table class="w3-table jb-margin-center jb-table-width-70">
        <tr>
            <th>Name</th>
            <th>Year</th>
            <th>Choices</th>
            <th>Number</th>
        </tr>
        {% for user in failedMales %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.year }}</td>
            {% if user.choice %}
            <td>{{ user.choice.firstChoice }},
                {{ user.choice.secondChoice }},
                {{ user.choice.thirdChoice }},
                {{ user.choice.fourthChoice }},
                {{ user.choice.fifthChoice }}
            </td>
            {% else %}
            <td>
                -
            </td>
            {% endif %}
            <td>{{ user.jerseyNumber.number }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
    <h3>Female Table</h3>
    <table class="w3-table jb-margin-center jb-table-width-70">
        <tr>
            <th>Name</th>
            <th>Year</th>
            <th>Choices</th>
            <th>Number</th>
        </tr>
        {% for user in failedFemales %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.year }}</td>
            {% if user.choice %}
            <td>{{ user.choice.firstChoice }},
                {{ user.choice.secondChoice }},
                {{ user.choice.thirdChoice }},
                {{ user.choice.fourthChoice }},
                {{ user.choice.fifthChoice }}
            </td>
            {% else %}
            <td>
                -
            </td>
            {% endif %}
            <td>{{ user.jerseyNumber.number }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/allocatePage.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-white w3-center w3-opacity w3-padding-32">
    <br><br>
    <h3>
        {{ message }}
    </h3>
</div>

<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
<form method="POST" action="">
    {{ form.hidden_tag() }}
        <div class="form-grop">
            <h4>Choose a year</h4>
            <br>
            {{ form.yearToAllocate(class="form-control form-control-lg") }}
        </div>
    <div class="form-grop">
        <br>{{ form.submit(class="w3-button")}}
    </div>
</form>
</div>

</div>
{% endblock content%}

jersey_bidder/templates/jersey_bidder/useradmin/allocateSingleUser.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-orange w3-center w3-opacity w3-padding-64">
    <br><br>
    <h4>Following is the list of all availible numbers left for {{user.name}} </h4>
</div>
<div class="w3-container w3-white w3-center w3-opacity w3-padding-16 jb-table-width-70 jb-margin-center">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="form-grop">
            <br>{{ form.assign.label(class="form-control-label") }}<br>
            {% if form.assign.errors %}
            {{ form.assign(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.assign.errors %}
                <span> {{ error }} </span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.assign(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-grop">
            <br>{{ form.submit(class="w3-button")}}
        </div>
    </form>
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/allocateSuccess.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-green w3-center w3-opacity w3-padding-64">
    <br><h4>No conflicts detected.</h4>
</div>
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-64">
    <table class="w3-table jb-margin-center jb-table-width-70">
        <tr>
            <th>Number</th>
            <th>Name</th>
            <th>Year</th>
            <th>roomNumber</th>
        </tr>
        {% for user in allUsersInYear %}
        <tr>
            <td>{{ user.jerseyNumber.number }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.year}}</td>
            <td>{{ user.roomNumber }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/availNumbers.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-green w3-center w3-opacity w3-padding-64">
    <br><h4>Avail Numbers to User</h4>
</div>
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-64">
        {% for number in availNumbers %}
            <div>{{ number.number }}</div>
        {% endfor %}
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/conflictUser.html
{% extends "layout.html" %}
{% block content %}
{% if conflictUsers %}
<div class="w3-container w3-orange w3-center w3-opacity w3-padding-32">
    <br><br>
    <h4>This is the list of all {{ gender }} users without numbers</h4>
</div>

<div class="w3-container w3-white w3-center w3-opacity w3-padding-16 jb-table-width-70 jb-margin-center">
    <table class="w3-table jb-margin-center">
        <tr>
            <th></th>
            <th class="jb-table-border jb-table-header">Name</th>
            <th class="jb-table-border jb-table-header">Choices</th>
            <th class="jb-table-border jb-table-header">Year</th>
            <th class="jb-table-border jb-table-header">Points</th>
            <th class="jb-table-border jb-table-header">Sports</th>
            <th class="jb-table-border jb-table-header">Unique Number Preference</th>
        </tr>
        {% for user in conflictUsers %}
            <td classs="w3-button"><a href="{{url_for('useradmin.adminAssign', user_id=user.id)}}"><i class="fa fa-pencil-square-o"></i></a></td>
            <td class="jb-table-border-bottom jb-table-border-left">{{ user.name }}</td>
            <td class="jb-table-border-bottom">
                {{ user.choice.firstChoice }}
                {{ user.choice.secondChoice }}
                {{ user.choice.thirdChoice }}
                {{ user.choice.fourthChoice }}
                {{ user.choice.fifthChoice }}
            </td>
            <td class="jb-table-border-bottom">{{ user.year }}</td>
            <td class="jb-table-border-bottom">{{ user.points }}</td>
            <td class="jb-table-border-bottom">
                {% for sport in user.sports %}
                {{ sport.sportName }}
                {% endfor %}
            </td>
            <td class="jb-table-border-bottom jb-table-border-right">
                {% if user.wantUniqueNumber %}
                Wants unique number
                {% else %}
                Agrees to share
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<div class="w3-container w3-green w3-center w3-opacity w3-padding-64">
    <br><br>
    <h4>All {{gender}} users have been allocated a number.</h4>
</div>
{% endif %}
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/fullNameListFemale.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
        <h3>
            <br>List of all users (Female)
        </h3>
</div>
<div class="w3-container w3-white w3-center w3-opacity w3-padding-16 jb-table-width-70 jb-margin-center">
        <table class="w3-table">
            <tr class="jb-table-header jb-table-border">
                <th class="jb-table-border">Name</th>
                <th class="jb-table-border">IHG Years</th>
                <th class="jb-table-border">Points</th>
                <th class="jb-table-border">Sports</th>
                <th class="jb-table-border">Choices</th>
                <th class="jb-table-border">Number</th>
                <th class="jb-table-border">Uniqueness preference</th>
            </tr>
            {% for user in users %}
            <tr class="jb-table-border">
                <td>{{ user.name }}</td>
                <td>{{ user.year }}</td>
                <td>{{ user.points }}</td>
                <td>
                    {% for sport in user.sports %}
                    {{ sport.sportName }}
                    {% endfor %}
                </td>
                <td>
                    {{ user.choice.firstChoice }}
                    {{ user.choice.secondChoice }}
                    {{ user.choice.thirdChoice }}
                    {{ user.choice.fourthChoice }}
                    {{ user.choice.fifthChoice }}
                </td>
                <td>{{ user.jerseyNumber.number }}</td>
                <td>
                {% if user.wantUniqueNumber %}
                    Wants unique number
                {% else %}
                    Agreed to share
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/fullNameListMale.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
        <h3>
            <br>List of all users (Male)
        </h3>
</div>
<div class="w3-container w3-white w3-center w3-opacity w3-padding-16 jb-table-width-70 jb-margin-center">
        <table class="w3-table">
            <tr class="jb-table-header jb-table-border">
                <th class="jb-table-border">Name</th>
                <th class="jb-table-border">IHG Years</th>
                <th class="jb-table-border">Points</th>
                <th class="jb-table-border">Sports</th>
                <th class="jb-table-border">Choices</th>
                <th class="jb-table-border">Number</th>
                <th class="jb-table-border">Unique Number Preference</th>
            </tr>
            {% for user in users %}
            <tr class="jb-table-border">
                <td>{{ user.name }}</td>
                <td>{{ user.year }}</td>
                <td>{{ user.points }}</td>
                <td>
                    {% for sport in user.sports %}
                    {{ sport.sportName }}
                    {% endfor %}
                </td>
                <td>
                    {{ user.choice.firstChoice }}
                    {{ user.choice.secondChoice }}
                    {{ user.choice.thirdChoice }}
                    {{ user.choice.fourthChoice }}
                    {{ user.choice.fifthChoice }}
                </td>
                <td>{{ user.jerseyNumber.number }}</td>
                <td>
                {% if user.wantUniqueNumber %}
                    Wants unique number
                {% else %}
                    Agrees to share
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/useradmin/selectYear.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-white w3-center w3-opacity w3-padding-32">
    <br><br>
    <h3>
        {{ message }}
    </h3>
</div>

<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="form-grop">
            <h4>Choose a year</h4>
            <br>
            <div class="jb-element-width-50 jb-margin-center">
                {{ form.yearToAllocate(class="form-control form-control-lg") }}
            </div>
        </div>
        <div class="form-grop">
            <br>{{ form.submit(class="w3-button")}}
        </div>
    </form>
</div>

</div>
{% endblock content%}

jersey_bidder/templates/jersey_bidder/useradmin/showMaleResultByYear.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
        <h3>
            <br>List of year {{year_id}} users (Male)
        </h3>
</div>
<div class="w3-container w3-white w3-center w3-opacity w3-padding-16 jb-table-width-70 jb-margin-center">
        <table class="w3-table">
            <tr class="jb-table-header jb-table-border">
                <th class="jb-table-border">Name</th>
                <th class="jb-table-border">IHG Years</th>
                <th class="jb-table-border">Points</th>
                <th class="jb-table-border">Sports</th>
                <th class="jb-table-border">Choices</th>
                <th class="jb-table-border">Number</th>
                <th class="jb-table-border">Uniqueness preference</th>
            </tr>
            {% for user in usersByYear %}
            <tr class="jb-table-border">
                <td>{{ user.name }}</td>
                <td>{{ user.year }}</td>
                <td>{{ user.points }}</td>
                <td>
                    {% for sport in user.sports %}
                    {{ sport.sportName }}
                    {% endfor %}
                </td>
                <td>
                    {{ user.choice.firstChoice }}
                    {{ user.choice.secondChoice }}
                    {{ user.choice.thirdChoice }}
                    {{ user.choice.fourthChoice }}
                    {{ user.choice.fifthChoice }}
                </td>
                <td>{{ user.jerseyNumber.number }}</td>
                <td>
                {% if user.wantUniqueNumber %}
                    Wants unique number
                {% else %}
                    Agreed to share
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}