jersey_bidder/main/routes.py
import json
from flask import Blueprint, request, render_template, url_for,redirect
from flask_wtf import Form
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_user, current_user, logout_user, login_required
from jersey_bidder.models import FlaskUser
main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('/jersey_bidder/main/home.html')
    
@main.route("/")
@main.route("/faqpage")
def faq():
    return render_template('/jersey_bidder/main/faq.html')

# @main.route("/")
# @main.route("/test")
# def test():
#     roles = FlaskUser.query.first().roles
#     return render_template('/jersey_bidder/main/testingPage.html', roles=roles)

jersey_bidder/user/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_user, logout_user, login_required
from flask_user import current_user

#local
from jersey_bidder.models import  User, Choice, FlaskUser
from jersey_bidder.user.forms import LoginForm
from jersey_bidder.utils import getUser


user = Blueprint('users', __name__)

@user.route("/login", methods=['GET','POST']) 
def login():
    form = LoginForm()
    if form.validate_on_submit():
        attemptedFlaskUser = FlaskUser.query.filter_by(username=form.userName.data).first()
        #if user and bcrypt.check_password_hash(user.password, form.password.data):
        if attemptedFlaskUser and form.password.data == attemptedFlaskUser.password:
            login_user(attemptedFlaskUser)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful, Please Check room number and password', 'danger')
    return render_template('/jersey_bidder/user/login.html', title='Login', form=form)

@user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

""" @user.route("/checkresult")
@login_required
def checkresult():
    user = getUser(current_user)
    return render_template("/jersey_bidder/user/checkResult.html", user=user) """

jersey_bidder/templates/jersey_bidder/main/faq.html
{% extends "layout.html" %}
{% block style %}
{% endblock style %}

{% block content %}
<div class="w3-light-blue w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
      <br>
      <br>
      <h1 class="jb-text-align-left">FAQ</h1><br>
      <h4 class="jb-text-align-left">Can't find the answer you are looking for? We have shared some of our
        most frequently
        asked questions to help you out!</h4>
  </div>
</div>

<div class="w3-white w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> What is the overall process?</h4>
    <span>
      Jersey bidding 19/20 will take place over the course of 4 days with 4 different waves of bidding and each gender
      will have 99 numbers to choose from (1-99)
      <br><br>
      Seniors who have taken part in three or more IHG seasons will bid first in the first wave followed by seniors with
      two IHG seasons, followed by seniors with one IHG season and lastly freshmen or seniors with no IHG participation
      will bid in the final wave.
      <br>
    </span>
  </div>
</div>

<div class="w3-light-grey w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> Can we share number with other Eusoffians?
    </h4>
    <span>
      For Eusoffians who have participated in at least 2 IHG seasons, sharing is not allowed by default unless he or she
      agrees to share (this preference can be edited in the 'bid' page).
      <br><br>
      For Euosffian who have participated in 1 IHG or less (generally year 1 and year 2), sharing of number is possible
      unless they have clashing sports.
      <br><br>
      In order for two Eusoffians to share a number, they must not have any sport in common.
    </span>
  </div>
</div>

<div class="w3-white w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> What do we have to do?</h4>
    <span>
      We will notify you when it is your turn to bid via Channel EH. Each wave will start at 6 AM and ends at 9 PM on
      the same day.
      <br><br>
      When it is your turn, you can first use the 'Indicate Preference' page to see potential bidders for a number.
      Once you have made your decision, go to the 'Bid' page to put down your top 5 choices.
      <br><br>
      After 9 PM, the system will not accept anymore bidding submissions. Numbers will be allocated to the bidders in
      this wave and bidders can use 'Check Result' to see their number.
    </span>
  </div>
</div>

<div class="w3-light-grey w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> What to do if I miss my bidding window?
    </h4>
    <span>Contact Brenda or Jiaying or any SMC Logistics member to notify them. SMC Logistics will then allocate you a
      number randomly.
    </span>
  </div>
</div>

<div class="w3-white w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> How does 'indicate preference' work?</h4>
    <span>In this page, you can see which number is really popular and their potential bidders. You can also use
      this page to deconflict with fellow Eusoffians if you happen to be wanting the same number. Indicating your
      preference in this page also helps other Eusoffians to make more informed decisions.
      .</span>
    </span>
  </div>
</div>

<div class="w3-light-grey w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> Who gets to bid first and why?</h4>
    <span>Priority to bid is determined by how many times an Euosffian have participated in IHG. For example, a year 4
      senior who has taken part in 3 IHGs will have a higher priority than a year 2 Eusoffian who has only taken part in
      1.
      <br><br>
      Note that year of study does not imply pirority - a year 2 Eusoffian who has taken part in 1 IHG has a higher
      priority than a year 3 senior who has never taken part in IHG before. If the number of times of participation is
      the same between two Euosffians, priority is determined by Bidding Points (see below).
    </span>
  </div>
</div>

<div class="w3-white w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> How are our bidding points determined?
    </h4>
    <span>Bidding Point is the sum of the following: <ul>
        <li>number of sports an Eusoffian is in (after first cut), each sport constitute as 1 point.</li>
        <li>leadership position in sports, each leadership role (captain only) constitute as 1 point.</li>
        <li>if an Eusoffian is representing NUS in any sports, each IVP/Sunig sport constitute as 1 point.</li>
      </ul>
      <br>For example, if Alice is in the NUS floorball team, is the captain of Eusoff Floorball and is in both Eusoff
      floorball and Football
      <br>then Alice will have: 1 (NUS floorball) + 1 (Captain) + 2 (Eusoff Floorball and
      Football) = 4 points
    </span>
  </div>
</div>

<div class="w3-light-grey w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> What if two Eusoffians have the exact same
      priority and bidding points?</h4>
    <span>The order will be randomly sorted.</span>
  </div>
</div>

<div class="w3-white w3-opacity w3-center w3-padding-64">
  <div class="jb-table-width-80 jb-margin-center jb-text-align-fulljustifed">
    <h4 class=""><i class="fa fa-question-circle fa-lg w3-hover-opacity"></i> Is Bidding Compulsory?</h4>
      <span>All Eusoffians are entitled to bid for a jersey number :)</span>
      <br>
      <br>
      <span>However, bidding is mandatory for atheletes from the following sports: Frisbee, Softball, Takraw, Netball, Floorball, Soccer, Handball, Volleyball</span>
  </div>
</div>

</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/main/home.html
{% extends 'layout.html' %}

{% block head %}
<h1></h1>
{% endblock head %}

{% block content %}
<!-- Header -->
<div class="jb-main-cover-background">
<header class="w3-container jb-main-cover-content jb-header w3-center w3-padding-276">
  <div class="">
  {% if current_user.is_authenticated %}
  <h1 class="w3-margin w3-jumbo">Welcome!</h1>
  <h3>Jersey Bidding Exercise 19/20</h3>
  </button>
  {% else %}
  <h1 class="w3-margin w3-jumbo ">Jersey Bidding 19/20</h1>
    <h1 class="jb-disable-link"><a href="{{ url_for('users.login') }}">Login</a></h1>
  {% endif %}
</div>
</div>
</header>
</header> 
{% endblock content %}

jersey_bidder/templates/jersey_bidder/main/testingPage.html
{% block content %}
{% for user in userlist %}
{{ user.roles }}
{{ user.id }}
{% endfor %}
{% endblock content%}