jersey_bidder/numbers/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField, SelectField, BooleanField
from wtforms.validators import DataRequired, Email, Length, EqualTo, ValidationError
from flask_login import current_user


class chopeNumberForm(FlaskForm):
    submit = SubmitField('I want this number')


class biddingFormSenior(FlaskForm):
    firstChoice = SelectField('First Choice', validators=[
                              DataRequired()], coerce=int)
    secondChoice = SelectField('Second Choice', validators=[
                               DataRequired()], coerce=int)
    thirdChoice = SelectField('Third Choice', validators=[
                              DataRequired()], coerce=int)
    fourthChoice = SelectField('Fourth Choice', validators=[
                               DataRequired()], coerce=int)
    fifthChoice = SelectField('Fifth Choice', validators=[
                              DataRequired()], coerce=int)
    wantUniqueNumber = SelectField('I want my number to be unique.',  coerce=int)
    submit = SubmitField('Submit my choices')

class biddingFormJunior(FlaskForm):
    firstChoice = SelectField('First Choice', validators=[
                              DataRequired()], coerce=int)
    secondChoice = SelectField('Second Choice', validators=[
                               DataRequired()], coerce=int)
    thirdChoice = SelectField('Third Choice', validators=[
                              DataRequired()], coerce=int)
    fourthChoice = SelectField('Fourth Choice', validators=[
                               DataRequired()], coerce=int)
    fifthChoice = SelectField('Fifth Choice', validators=[
                              DataRequired()], coerce=int)
    submit = SubmitField('Submit my choices')

class allocateForm(FlaskForm):
    yearToAllocate = SelectField('Year To Allocate', validators=[DataRequired()], coerce=int)
    submit = SubmitField('Allocate!')

jersey_bidder/numbers/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_user, logout_user, login_required
from datetime import datetime
from flask_user import roles_required, current_user

# local
from jersey_bidder.models import User, Choice, JerseyNumber
from jersey_bidder.numbers.forms import biddingFormSenior, chopeNumberForm, allocateForm, biddingFormJunior
from jersey_bidder.numbers.utils import typeCastFormData
from jersey_bidder import db
from jersey_bidder.utils import getUser


numbers = Blueprint('numbers', __name__)


@numbers.route("/preference", methods=['GET', 'POST'])
def showNumber():
    currentUser = getUser(current_user)
    numbers = JerseyNumber.query.filter(
        JerseyNumber.gender_id == currentUser.gender_id).order_by(JerseyNumber.number).all()
        
    return render_template('/jersey_bidder/numbers/prefViewAll.html', title='Preference Page', numbers=numbers)


@numbers.route("/preference/<int:jerseyNumber_id>", methods=['GET', 'POST'])
def showSingleNumber(jerseyNumber_id):
    number = JerseyNumber.query.get_or_404(jerseyNumber_id)
    interestedUsers = User.query.filter(
        User.preference_id == number.id and User.gender_id == number.gender_id).all()
    return render_template('/jersey_bidder/numbers/prefViewSingleNumber.html', title='Preference Page', number=number, interestedUsers=interestedUsers)


@numbers.route("/preference/chope/<int:jerseyNumber_id>", methods=['GET', 'POST'])
def chopeSingleNumber(jerseyNumber_id):
    number = JerseyNumber.query.get_or_404(jerseyNumber_id)
    newNumber = number = JerseyNumber.query.get_or_404(jerseyNumber_id)
    currentUser = getUser(current_user)
    currentUser.preference_id = newNumber.id
    db.session.commit()

    return render_template('/jersey_bidder/numbers/prefChopeNumber.html', title='Chope', newNumber=newNumber)

@numbers.route("/bidder/choice", methods=['GET','POST'])
@roles_required('Bidder')
def routeYearToBid():
    currentUser = getUser(current_user)
    if currentUser.year > 1:
        return redirect(url_for('numbers.bidNumberSenior'))
    else:
        return redirect(url_for('numbers.bidNumberJunior'))


@numbers.route("/bidding/senior", methods=['GET', 'POST'])
@roles_required('Bidder')
def bidNumberSenior():

    # initialize form and populate choices
    form = biddingFormSenior()
    currentUser = getUser(current_user)
    
    form.firstChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.secondChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.thirdChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fourthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fifthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.wantUniqueNumber.choices = [(1,'Yes'),(2,'No')]

    # if current user has submitted a choice, redirect to editing page
    if currentUser.choice:
        return redirect(url_for('numbers.editNumberSenior')) 

    # fetch the current user's year for further validation, only 2+ years in IHG can choose unique option
    userYear = getUser(current_user).year

    if form.validate_on_submit():
        submitDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        #type cast an integer from form into bool, wantUniqueNumber is either True or False (bool)
        wantUniqueNumber = typeCastFormData(form.wantUniqueNumber.data)
        #update the user's "wantUniqueNumber" accordingly
        getUser(current_user).wantUniqueNumber = wantUniqueNumber

        choice = Choice(submitDatetime=submitDate, firstChoice=form.firstChoice.data, secondChoice=form.secondChoice.data,
                        thirdChoice=form.thirdChoice.data, fourthChoice=form.fourthChoice.data, fifthChoice=form.fifthChoice.data,
                        user_id=currentUser.id)

        db.session.add(choice)
        db.session.commit()

        successMessage = "Your submission has been registered."
        return render_template('/jersey_bidder/numbers/biddingSuccess.html', successMessage=successMessage)

    return render_template('/jersey_bidder/numbers/biddingPageSenior.html', title='Bidding', form=form, userYear=userYear)

@numbers.route("/bidding/junior", methods=['GET', 'POST'])
@roles_required('Bidder')
def bidNumberJunior():

    # initialize form and populate choices
    form = biddingFormJunior()
    currentUser = getUser(current_user)
    
    form.firstChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.secondChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.thirdChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fourthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fifthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    # if current user has submitted a choice, redirect to editing page
    if currentUser.choice:
        return redirect(url_for('numbers.editNumberJunior'))

    # fetch the current user's year for further validation, only 2+ years in IHG can choose unique option
    userYear = getUser(current_user).year

    if form.validate_on_submit():
        submitDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        choice = Choice(submitDatetime=submitDate, firstChoice=form.firstChoice.data, secondChoice=form.secondChoice.data,
                        thirdChoice=form.thirdChoice.data, fourthChoice=form.fourthChoice.data, fifthChoice=form.fifthChoice.data,
                        user_id=currentUser.id)

        db.session.add(choice)
        db.session.commit()

        successMessage = "Your submission has been registered."
        return render_template('/jersey_bidder/numbers/biddingSuccess.html', successMessage=successMessage)

    return render_template('/jersey_bidder/numbers/biddingPageJunior.html', title='Bidding', form=form, userYear=userYear)



@numbers.route("/bidding/editchoice/senior", methods=['GET', 'POST'])
@roles_required('Bidder')
def editNumberSenior():

    # get User Model from FlaskUser
    currentUser = getUser(current_user)

    # initialize form and populate choices
    form = biddingFormSenior()
    form.firstChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.secondChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.thirdChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fourthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.fifthChoice.choices = [(entries.number, entries.number) for entries in JerseyNumber.query.filter(
        JerseyNumber.isTaken == False, JerseyNumber.gender_id == currentUser.gender_id)]
    form.wantUniqueNumber.choices = [(1,'Yes'),(2,'No')]

    # fetch current users' previous choice and unique preference to display on the site 
    currentChoice = Choice.query.filter(
        Choice.user_id == currentUser.id).first()

    # fetch the current user's year for further validation
    userYear = getUser(current_user).year
    wantUniqueNumber = getUser(current_user).wantUniqueNumber

    if form.validate_on_submit():
        submitDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        #type cast an integer from form into bool, wantUniqueNumber is either True or False (bool)
        wantUniqueNumber = typeCastFormData(form.wantUniqueNumber.data)
        #update the user's "wantUniqueNumber" accordingly
        getUser(current_user).wantUniqueNumber = wantUniqueNumber

        newChoice = Choice(submitDatetime=submitDate, firstChoice=form.firstChoice.data, secondChoice=form.secondChoice.data,
                           thirdChoice=form.thirdChoice.data, fourthChoice=form.fourthChoice.data, fifthChoice=form.fifthChoice.data,
                           user_id=currentUser.id)



        # remove the previous submission and commit the latest one
        db.session.delete(currentChoice)
        db.session.add(newChoice)
        db.session.commit()

        successMessage = "Your previous submission has been updated"
        return render_template('/jersey_bidder/numbers/biddingSuccess.html', successMessage=successMessage)

jersey_bidder/templates/jersey_bidder/numbers/biddingEdit.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
    <h4 class="w3-text-black">
        <br>
        <br>
        <h4>My Previous Choices</h4>
    </h4>
    <div class="jb-grid-container-choices jb-table-width-80 jb-margin-center">
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">First Choice <br>{{ currentChoice.firstChoice }}</div>
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">Second Choice <br> {{ currentChoice.secondChoice }}
        </div>
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">Third Choice <br>{{ currentChoice.thirdChoice }}</div>
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">Fourth Choice <br> {{ currentChoice.fourthChoice }}
        </div>
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">Fifth Choice <br> {{ currentChoice.fifthChoice }}
        </div>
    </div>
    <h4>My New Choices</h4>
    <form method="POST" action="">
        <div class="jb-grid-container-choices jb-table-width-80 jb-margin-center">
            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.firstChoice.label(class="form-control-label") }}<br>
                {% if form.firstChoice.errors %}
                {{ form.firstChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.firstChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.firstChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.secondChoice.label(class="form-control-label") }}<br>
                {% if form.secondChoice.errors %}
                {{ form.secondChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.secondChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.secondChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.thirdChoice.label(class="form-control-label") }}<br>
                {% if form.thirdChoice.errors %}
                {{ form.thirdChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.thirdChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.thirdChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.fourthChoice.label(class="form-control-label") }}<br>
                {% if form.fourthChoice.errors %}
                {{ form.fourthChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.fourthChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.fourthChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>


            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.fifthChoice.label(class="form-control-label") }}<br>
                {% if form.fifthChoice.errors %}
                {{ form.fifthChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.fifthChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.fifthChoice(class="form-control form-control-lg") }}
                </div>
                <br>
                {% endif %}
            </div>
        </div>
        {{ form.hidden_tag() }}
        <div class="form-grop">
            {% if userYear > 1 %}
                {% if wantUniqueNumber %}
                <br><h4>Your previous submission indicate you want your number to be unique.</h4>
                {% else %}
                <br><h4>Your previous submission indicate you agree to share your number with other Eusoffians.</h4>
                {% endif %}
            <div class="form-grop">
                <br>{{ form.wantUniqueNumber.label(class="form-control-label") }}<br>
                {% if form.wantUniqueNumber.errors %}
                {{ form.wantUniqueNumber(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.wantUniqueNumber.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
            </div>
            <div class="jb-table-width-50 jb-margin-center">
                {{ form.wantUniqueNumber(class="form-control form-control-lg") }}
            </div>
            {% endif %}
        </div><br>
        {% endif %}
        <div class="form-group">
            {{ form.submit(class="w3-button jb-button")}}
        </div>
    </form>
</div>
</div>
{% endblock content%}

jersey_bidder/templates/jersey_bidder/numbers/biddingEditJunior.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
    <h4 class="w3-text-black">
        <br>
        <br>
        <h4>My Previous Choices</h4>
    </h4>
    <div class="jb-grid-container-choices jb-table-width-80 jb-margin-center">
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">First Choice <br>{{ currentChoice.firstChoice }}</div>
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">Second Choice <br> {{ currentChoice.secondChoice }}
        </div>
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">Third Choice <br>{{ currentChoice.thirdChoice }}</div>
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">Fourth Choice <br> {{ currentChoice.fourthChoice }}
        </div>
        <div class="jb-grid-item-choices jb-margin-top-bottom-20">Fifth Choice <br> {{ currentChoice.fifthChoice }}
        </div>
    </div>
    <h4>My New Choices</h4>
    <form method="POST" action="">
        <div class="jb-grid-container-choices jb-table-width-80 jb-margin-center">
            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.firstChoice.label(class="form-control-label") }}<br>
                {% if form.firstChoice.errors %}
                {{ form.firstChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.firstChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.firstChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.secondChoice.label(class="form-control-label") }}<br>
                {% if form.secondChoice.errors %}
                {{ form.secondChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.secondChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.secondChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.thirdChoice.label(class="form-control-label") }}<br>
                {% if form.thirdChoice.errors %}
                {{ form.thirdChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.thirdChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.thirdChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.fourthChoice.label(class="form-control-label") }}<br>
                {% if form.fourthChoice.errors %}
                {{ form.fourthChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.fourthChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.fourthChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>


            <div class="form-grop jb-grid-item-choices">
                <br>New {{ form.fifthChoice.label(class="form-control-label") }}<br>
                {% if form.fifthChoice.errors %}
                {{ form.fifthChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.fifthChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.fifthChoice(class="form-control form-control-lg") }}
                </div>
                <br>
                {% endif %}
            </div>
        </div>
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.submit(class="w3-button jb-button")}}
        </div>
    </form>
</div>
</div>
{% endblock content%}

jersey_bidder/templates/jersey_bidder/numbers/biddingPage.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
    <h4 class="w3-text-black">
        <br>
        <br>Select Your Top 5 Choices
        <br>
    </h4>
    <form method="POST" action="">
        <div class="jb-grid-container-choices jb-table-width-80 jb-margin-center">
            <div class="form-grop jb-grid-item-choices">
                <br>{{ form.firstChoice.label(class="form-control-label") }}<br>
                {% if form.firstChoice.errors %}
                {{ form.firstChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.firstChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.firstChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>{{ form.secondChoice.label(class="form-control-label") }}<br>
                {% if form.secondChoice.errors %}
                {{ form.secondChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.secondChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.secondChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>{{ form.thirdChoice.label(class="form-control-label") }}<br>
                {% if form.thirdChoice.errors %}
                {{ form.thirdChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.thirdChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.thirdChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>

            <div class="form-grop jb-grid-item-choices">
                <br>{{ form.fourthChoice.label(class="form-control-label") }}<br>
                {% if form.fourthChoice.errors %}
                {{ form.fourthChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.fourthChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.fourthChoice(class="form-control form-control-lg") }}
                </div>
                {% endif %}
            </div>


            <div class="form-grop jb-grid-item-choices">
                <br>{{ form.fifthChoice.label(class="form-control-label") }}<br>
                {% if form.fifthChoice.errors %}
                {{ form.fifthChoice(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.fifthChoice.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jb-table-width-50 jb-margin-center">
                    {{ form.fifthChoice(class="form-control form-control-lg") }}
                </div>
                <br>
                {% endif %}
            </div>
        </div>
        {{ form.hidden_tag() }}
        <div class="form-grop">
            {% if userYear > 1 %}
            <div class="form-grop">
                <br>{{ form.wantUniqueNumber.label(class="form-control-label") }}<br>
                {% if form.wantUniqueNumber.errors %}
                {{ form.wantUniqueNumber(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.wantUniqueNumber.errors %}
                    <span> {{ error }} </span>
                    {% endfor %}
                </div>
                {% else %}
            </div>
            <div class="jb-table-width-50 jb-margin-center">
                {{ form.wantUniqueNumber(class="form-control form-control-lg") }}
            </div>
            {% endif %}
        </div><br>
        {% endif %}
        <div class="form-group">
            {{ form.submit(class="w3-button jb-button")}}
        </div>
    </form>
</div>
</div>
{% endblock content%}

jersey_bidder/templates/jersey_bidder/numbers/biddingSuccess.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-green w3-center w3-opacity w3-padding-64">
    <h4>
        <br>{{ successMessage }}<br>
        <br><a class="jb-button" href="{{ url_for('numbers.routeYearToBid')}}">Edit my choices</a>
    </h4>
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/numbers/prefChopeNumber.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-green w3-center w3-opacity w3-padding-64">
    <br>
    <h4>
        Your prefrence has been registered.
    </h4>
    <h4>
        <br><a class="jb-button" href="{{ url_for('numbers.showSingleNumber', jerseyNumber_id=newNumber.id)}}">Go back</a>
    </h4>
</div>
{% endblock content %}

jersey_bidder/templates/jersey_bidder/numbers/prefViewAll.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-64">
    <h4>
        <br>Choose a number to see who is bidding for it.
    </h4>
</div>

<div class="w3-container w3-white w3-opacity">
    <div class="jb-grid-container jb-table-width-80 jb-margin-center w3-padding-32">
        {% for number in numbers %}
        <a class="jb-disable-link" href="{{ url_for('numbers.showSingleNumber', jerseyNumber_id=number.id) }}">
            <div class="jb-grid-item jb-margin-top-bottom-20">{{ number.number}}</div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content%}

jersey_bidder/templates/jersey_bidder/numbers/prefViewSingleNumber.html
{% extends "layout.html" %}
{% block content %}
<div class="w3-container w3-light-grey w3-center w3-opacity w3-padding-32">
    <h4>
        <br><br>Chosen Number: {{ number.number }}
    </h4>
</div>

<div class="w3-container w3-white w3-center w3-opacity w3-padding-16 jb-table-width-80 jb-margin-center">
    <h4>
        <br>Eusoffians who are currently interested in this number.
    </h4>
    <br>
    <table class="w3-table">
        <tr>
            <th class="jb-table-header jb-table-border">Name</th>
            <th class="jb-table-header jb-table-border">Years of IHG played</th>
            <th class="jb-table-header jb-table-border">Sports</th>
        </tr>

        {% for user in interestedUsers %}
        <tr>
            <td class="jb-table-border-bottom">{{user.name}}</td>
            <td class="jb-table-border-bottom">{{user.year}}</td>
            <td class="jb-table-border-bottom">
                {% if user.sports %}
                {% for sport in user.sports %}
                {{ sport.sportName }}
                {% endfor %}
                {% else %}
                -
                {% endif %}
            </td>
            <td>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
<br>
<form method="POST" action="">
    <div class="w3-container w3-white w3-center w3-opacity">
        <a href="{{url_for('numbers.chopeSingleNumber', jerseyNumber_id=number.id)}}" class="jb-button">I want this number!</a>
    </div>
</form>
{% endblock content %}